public enum FoilMakerNetworkProtocol$MSG_DETAIL_T
{
  SUCCESS,  INVALIDUSERNAME,  INVALIDUSERPASSWORD,  USERALREADYEXISTS,  UNKNOWNUSER,  USERALREADYLOGGEDIN,  GAMEKEYNOTFOUND,  NO_CONNECTION_TO_SERVER,  ERROR_OPENING_NETWORK_CONNECTION,  USERNOTLOGGEDIN,  USERNOTGAMELEADER,  INVALIDGAMETOKEN,  UNEXPECTEDMESSAGETYPE,  INVALIDMESSAGEFORMAT,  FAILURE;
  
  private FoilMakerNetworkProtocol$MSG_DETAIL_T() {}
}
