public class FoilMakerNetworkProtocol
{
  public static final String SEPARATOR = "--";
  public static final int LOGIN_TOKEN_LENGTH = 10;
  public static final int GAME_KEY_LENGTH = 3;
  
  public static enum MSG_TYPE
  {
    CREATENEWUSER,  LOGIN,  LOGOUT,  STARTNEWGAME,  JOINGAME,  ALLPARTICIPANTSHAVEJOINED,  PLAYERCHOICE,  PLAYERSUGGESTION,  NEWPARTICIPANT,  RESPONSE,  NEWGAMEWORD,  ROUNDOPTIONS,  ROUNDRESULT,  GAMEOVER;
    
    private MSG_TYPE() {}
  }
  
  public static enum MSG_DETAIL_T
  {
    SUCCESS,  INVALIDUSERNAME,  INVALIDUSERPASSWORD,  USERALREADYEXISTS,  UNKNOWNUSER,  USERALREADYLOGGEDIN,  GAMEKEYNOTFOUND,  NO_CONNECTION_TO_SERVER,  ERROR_OPENING_NETWORK_CONNECTION,  USERNOTLOGGEDIN,  USERNOTGAMELEADER,  INVALIDGAMETOKEN,  UNEXPECTEDMESSAGETYPE,  INVALIDMESSAGEFORMAT,  FAILURE;
    
    private MSG_DETAIL_T() {}
  }
}
