public enum FoilMakerNetworkProtocol$MSG_TYPE
{
  CREATENEWUSER,  LOGIN,  LOGOUT,  STARTNEWGAME,  JOINGAME,  ALLPARTICIPANTSHAVEJOINED,  PLAYERCHOICE,  PLAYERSUGGESTION,  NEWPARTICIPANT,  RESPONSE,  NEWGAMEWORD,  ROUNDOPTIONS,  ROUNDRESULT,  GAMEOVER;
  
  private FoilMakerNetworkProtocol$MSG_TYPE() {}
}
