 enum FoilMakerClientView$ViewNames
{
  LOGINVIEW,  CHOOSEGAMEVIEW,  NEWGAMEKEYVIEW,  ENTERGAMEKEYVIEW,  WAITINGFORLEADERVIEW,  ENTERSUGGESTIONVIEW,  WAITINGFOROTHERSVIEW,  PICKOPTIONVIEW,  ROUNDRESULTVIEW;
  
  private FoilMakerClientView$ViewNames() {}
}
